import type { NextRequest } from 'next/server';

function parseOrigin(value: string): URL | null {
  try {
    const url = new URL(value);
    if (
      !['http:', 'https:'].includes(url.protocol) ||
      url.username ||
      url.password ||
      url.pathname !== '/' ||
      url.search ||
      url.hash ||
      value.includes('\\') ||
      value.includes(',')
    )
      return null;
    return url;
  } catch {
    return null;
  }
}

/**
 * Return the verified browser-facing origin, or reject the login request.
 * Next's custom server can build nextUrl from its bind address (0.0.0.0),
 * which is not necessarily the public origin. Fetch Metadata is generated by
 * the browser and cannot be set by page scripts. Never trust arbitrary
 * X-Forwarded-Host/Proto headers as an origin allowlist.
 */
export function getKeyLoginRequestOrigin(request: NextRequest): URL | null {
  const site = request.headers.get('sec-fetch-site');
  // Other subdomains are not trusted to log a user into this origin either.
  if (site === 'cross-site' || site === 'same-site') return null;

  const rawOrigin = request.headers.get('origin');
  let source: URL | null = null;
  if (rawOrigin !== null) {
    source = parseOrigin(rawOrigin);
    if (!source) return null; // Includes opaque Origin: null.
  } else {
    const referer = request.headers.get('referer');
    if (referer) {
      try {
        const url = new URL(referer);
        if (url.username || url.password) return null;
        source = parseOrigin(url.origin);
        if (!source) return null;
      } catch {
        return null;
      }
    }
  }

  // Optional explicit origin for reverse proxies / older browsers without
  // Fetch Metadata. An invalid configured origin fails closed.
  const configured = process.env.SITE_PUBLIC_URL?.trim();
  if (configured) {
    const target = parseOrigin(configured);
    return target && source?.origin === target.origin ? source : null;
  }

  if (site === 'same-origin') {
    return source || parseOrigin(request.nextUrl.origin);
  }

  // Fallback for browsers without Sec-Fetch-* (e.g. HTTP on a LAN address).
  // Host represents the actual HTTP target, unlike the custom server bind URL.
  if (!source) return null;
  const host = request.headers.get('host');
  const target = host
    ? parseOrigin(`${request.nextUrl.protocol}//${host}`)
    : parseOrigin(request.nextUrl.origin);
  return target && source.origin === target.origin ? source : null;
}
