name = "moontvplus"
main = ".opennextjs/cloudflare/worker.js"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]
account_id = "04813f80860d3dc12e0030716b89d1c4"

[[d1_databases]]
binding = "DB"
database_name = "moontv-db"
database_id = "1c18ecae-9000-4494-aacc-99adc515e9ca"
